Feature/frontend
DreamLab/dl-academy-waw-1 pull request #4
Opened 2018-04-19 16:05 UTC by Spaceinvaderr

widoki i css

2018-04-19 20:53 UTC, iwko commented on step2/app.js
> +app.use('/api/', router);
Niepotrzebna zmiana

2018-04-19 20:53 UTC, iwko commented on step3/app.js
> +app.use('/api/', router);
jw

2018-04-20 07:55 UTC, wreszelewski commented on _additional/frontend/index.html
> +        <script>
Skrypt bym dał do osobnego pliku, IMO łatwiej będzie czytać

2018-04-20 07:55 UTC, wreszelewski commented on _additional/frontend/index.html
> +                            var czas = timestamp.toUTCString().slice(0, 22);
fajny byłby jeden język w nazwach zmiennych:)

2018-04-20 07:56 UTC, wreszelewski commented on _additional/frontend/index.html
> +                                $('#messages').append('<div id="' + data.messages[i].id + '"><div class="messageWrapper"><div class="messageContent">' + '<div class="username">' + data.messages[i].us
Nie lepiej tu skorystać z tych template stringów ``?

2018-04-20 07:57 UTC, iwko commented on _additional/frontend/index.html
> +            var data = {};
Dlaczego nie uzywasz `let` i `const`

2018-04-20 07:57 UTC, wreszelewski commented on _additional/frontend/index.html
> +                        showMessages();
Ja bym tego tu nie wywoływał, wiadomości powinny się odświeżać cyklicznie, np co 0,5s. Człowiek powinien móc szybko zobaczyć nowe wiadomości, nie dopiero po wysłaniu kolejnej.

2018-04-20 07:58 UTC, wreszelewski commented on _additional/frontend/index.html
> +                        showMessages();
jw

2018-04-20 07:58 UTC, wreszelewski commented on _additional/frontend/index.html
> +                        $("#textInput").css('display', 'block');
a może te dwa wrzucić w jeden div zawierający?

2018-04-20 07:59 UTC, wreszelewski commented on _additional/frontend/index.html
> +                        alert(JSON.stringify(response.responseJSON.error));
ten alert jest strasznie brzydki, nie ma jakichś takich okienek w bootstrapie?

2018-04-20 07:59 UTC, wreszelewski commented on _additional/frontend/index.html
> +                        console.log(JSON.stringify(response));
W funkcji niżej jest alert, tu console.log, może lepiej się zdecydoać na jedno?

2018-04-20 07:59 UTC, wreszelewski commented on _additional/frontend/index.html
> +                        alert(JSON.stringify(response.responseJSON.error));
alert => jakiś popup z bootstrapa?

2018-04-20 09:49 UTC, kmoskwiak commented on _additional/frontend/index.html
> +                    url: 'http://localhost:3000/api/messages',
zahardkodowany localhost

2018-04-20 09:53 UTC, kmoskwiak commented on _additional/frontend/index.html
> +                    url: 'http://localhost:3000/api/connect',
zahardkodowany localhost

2018-04-20 09:55 UTC, kmoskwiak commented on _additional/frontend/index.html
> +                        showMessages();
showMessage w tym miejscu ma jedną zaletę - wiadomość napisana przez użytkownika od razu pojawia się na liście - co jest oczekiwane z punktu widzenia piszącego

2018-04-20 10:00 UTC, kmoskwiak commented on _additional/frontend/index.html
> +                    dataType: 'json',
json pisane raz wielkimi raz małymi

2018-04-20 10:02 UTC, kmoskwiak commented on _additional/frontend/index.html
> +                    url: 'http://localhost:3000/api/disconnect',
localhost

2018-04-20 13:28 UTC, iwko approved these changes

2018-04-22 16:37 UTC, iwko commented on _additional/frontend/step3/index.html
> +                        <button type="submit" class="btn btn-primary mb-2">Wyloguj</button>
Zmienmy wyloguj na logout

2018-04-22 16:37 UTC, iwko commented on _additional/frontend/step3/index.html
> +                        <button type="submit" class="btn btn-primary">Wyślij</button>
Zmieńmy wyślij na send

2018-04-23 13:06 UTC, wreszelewski commented on _additional/frontend/step2/index.html
> +        <script>
Do osobnego pliku?

2018-04-23 13:12 UTC, wreszelewski commented on _additional/frontend/step3/index.html
> +            function getUsers () {
raczej mało istotne, ale jak niżej jest show to tu też mogłoby być show

2018-04-23 13:14 UTC, wreszelewski commented on _additional/frontend/step3/index.html
> +                                console.log(data.users[i]);
Zastanawiam się czy to do wywalennia czy do dodania w analogicznym miejscu w funkcji niżej.

2018-04-23 13:15 UTC, wreszelewski commented on _additional/frontend/step3/index.html
> +                <form id="loginForm" method="POST" action="/">
to method jest potrzebne?

2018-04-23 13:16 UTC, wreszelewski commented on _additional/frontend/step3/index.html
> +                    <form id="messageForm" method="POST">
method jest potrzebne?

2018-04-23 13:19 UTC, wreszelewski commented on _additional/frontend/step3/index.html
> +                                $('#messages').append('<div id="' + data.messages[i].id + '"><div class="messageWrapper"><div class="messageContent">' + '<div class="username">' + data.messages[i].us
Może to składanie wyrzucić do funkcji? Zastosować to nowoczesne składanie stringów przy pomocy ``?

2018-04-23 13:20 UTC, wreszelewski commented on _additional/frontend/step3/index.html
> +                            var elem = document.getElementById('messages');
Zastanawiam się czy to trzeba po każdej wiadomości wołać, czy wystarczy raz, po dodaniu wszystkich z nowej paczki

2018-04-23 13:22 UTC, wreszelewski commented on _additional/frontend/step3/index.html
> +           function refreshMessages () {
nazwa tej funkcji jest troszkę myląca - w tej chwili właściwie ona odświeża cały widok.

2018-04-23 13:22 UTC, wreszelewski commented on _additional/frontend/step3/index.html
> +                        showMessages();
To jest potrzebne? Ten refresher nam tego nie załatwi?

2018-04-23 15:27 UTC, iwko commented on _additional/frontend/front.js
> +                            // if(!currentUsers.has(data.users[i])){
niepotrzebny komentarz

2018-04-24 06:46 UTC, wreszelewski commented on _additional/frontend/front.js
> +                        refreshMessages();
To tu jest potrzebne? Czy to nam nie spowoduje uruchomienia jakby drugiej instancji refreshera?

2018-04-24 06:46 UTC, wreszelewski commented on _additional/frontend/front.js
> +                        showMessages();
To tutaj chyba też nie potrzebne - powinno samo co 0,5s się odświeżać

2018-04-24 06:47 UTC, wreszelewski commented on _additional/frontend/front.js
> +                                $('#messages').append('<div id="' + data.messages[i].id + '"><div class="messageWrapper"><div class="messageContent">' + '<div class="username">' + data.messages[i].us
To do osobnej funkcji? Albo z wykorzystaniem ``? W ten sposób to bardzo ciężko czytać. W osobnej funkcji można by zrobić linia pod linią, byłoby widać co tu jest.

2018-04-24 06:48 UTC, wreszelewski commented on _additional/frontend/front.js
> +            $('#messages').load(refreshMessages);
to jest potrzebne jeżeli refresh jest wywołany wyżej?

2018-04-24 08:02 UTC, wreszelewski commented on _additional/frontend/front.js
> +                        refreshMessages();
To tu jest chyba niepotrzebne

2018-04-24 08:02 UTC, wreszelewski commented on _additional/frontend/front.js
> +            $('#messages').load(refreshMessages);
To jest tu chyba niepotrzebne

2018-04-24 09:17 UTC, wreszelewski approved these changes

2018-04-24 11:06 UTC, nivlheim requested changes
Console.error() zamiast console.log() przy błędach i będzie git.

2018-04-24 11:06 UTC, nivlheim commented on _additional/frontend/step2/index.html
> +        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossor
Dla pewności wrzuciłbym bootstrapa, jquery i inne takie do repo na wypadek problemów z internetem.

2018-04-24 11:06 UTC, nivlheim commented on _additional/frontend/step3/index.html
> +                    data: { 'username': name },
Nazwy kluczy w ciapkach czy nie? Zdecyduj się. :D

2018-04-24 11:06 UTC, nivlheim commented on step2/app.js
> +app.use(express.static('../_additional/frontend/step2'));
Ja bym chyba to wyrzucił do oddzielnej aplikacji aby nie zaciemnić pisanego przez uczestników kodu. Co inni o tym myślą?

2018-04-24 11:06 UTC, nivlheim commented on step2/app.js
> +app.use(express.static('../_additional/frontend/step2'));
Ok, nevermind.

2018-04-24 11:06 UTC, nivlheim commented on _additional/frontend/step3/index.html
> +                <form id="loginForm" method="POST" action="/">
Chyba dobrze aby było to napisane wprost dla pewności.

2018-04-24 11:06 UTC, nivlheim commented on _additional/frontend/front.js
> +                                console.log(data.users[i]);
Jakiś porzucony `console.log`

2018-04-24 11:06 UTC, nivlheim commented on _additional/frontend/front.js
> +                        console.log(JSON.stringify(response));
A nie `console.error`?

2018-04-24 11:06 UTC, nivlheim commented on _additional/frontend/front.js
> +                        console.log(JSON.stringify(response));
`console.error`?

2018-04-24 11:06 UTC, nivlheim commented on _additional/frontend/front.js
> +                        console.log(JSON.stringify(response));
`console.error()`

2018-04-24 11:10 UTC, nivlheim approved these changes
Lepiej nie będzie.

2018-04-24 11:10 UTC, nivlheim commented on _additional/frontend/front.js
> +            var users = {};
8 spacji wcięcia?!

2018-04-24 11:19 UTC, kmoskwiak requested changes

2018-04-24 11:19 UTC, kmoskwiak commented on _additional/frontend/front.js
> +                            console.log(data.users[i]);
console.log spamuje console niepotrzebnie, jak będą jakieś błędy do debugowania to ludzie zgłupieją

2018-04-24 11:19 UTC, kmoskwiak commented on _additional/frontend/index.html
> +        <section id="loginForm">
zdublowane `id` loginForm w dokumencie

2018-04-24 11:19 UTC, kmoskwiak commented on _additional/frontend/index.html
> +                <form id="loginForm" action="/">
zdublowane `id` loginForm w dokumencie

2018-04-24 11:19 UTC, kmoskwiak commented on _additional/frontend/front.js
> +            var users = {};
wcięcia niepotrzebne

2018-04-24 11:19 UTC, kmoskwiak commented on _additional/frontend/front.js
> +                            '<div class="messageBody" id="messageBody_'  +i++ + '">' + message.body + '</div>' +
1) id jest zawsze messageBody_0 dublują się id w dokumencie
2) co robi ta konstrukcja `  +i++ + `?

2018-04-24 11:19 UTC, kmoskwiak commented on _additional/frontend/front.js
> +                    dataType: "JSON",
tak przy okazji raz jest `'` a raz `"`

2018-04-24 11:39 UTC, kmoskwiak approved these changes

2018-04-24 11:39 UTC, kmoskwiak commented
jusz

2018-04-24 12:12 UTC, merged